import { useState } from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
export default function App() {
  const [punchedIn, setPunchedIn] = useState(false);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><Text style={styles.eyebrow}>MONDAY, JULY 25</Text><Text style={styles.title}>Good morning, Jordan</Text><Text style={styles.muted}>Here’s your workday at a glance.</Text><View style={styles.punchCard}><Text style={styles.cardLabel}>TODAY’S ATTENDANCE</Text><Text style={styles.time}>{punchedIn ? '09:12 AM' : 'Not clocked in'}</Text><TouchableOpacity style={styles.button} onPress={() => setPunchedIn(!punchedIn)}><Text style={styles.buttonText}>{punchedIn ? 'Clock out' : 'Clock in'}</Text></TouchableOpacity></View><View style={styles.grid}><Metric label="Leave balance" value="18 days"/><Metric label="This month" value="₹1.2L"/><Metric label="Next payslip" value="Aug 01"/><Metric label="Open tasks" value="3"/></View><Text style={styles.section}>Quick actions</Text><View style={styles.actions}><Action label="Apply leave"/><Action label="View payslips"/><Action label="My attendance"/></View></ScrollView><View style={styles.tabs}><Tab label="Home" active/><Tab label="Attendance"/><Tab label="Leave"/><Tab label="Payslips"/><Tab label="More"/></View></SafeAreaView>
}
function Metric({label,value}:{label:string,value:string}) { return <View style={styles.metric}><Text style={styles.muted}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View> }
function Action({label}:{label:string}) { return <TouchableOpacity style={styles.action}><Text style={styles.actionText}>{label}</Text></TouchableOpacity> }
function Tab({label,active}:{label:string,active?:boolean}) { return <TouchableOpacity style={styles.tab}><Text style={[styles.tabText,active&&styles.tabActive]}>{label}</Text></TouchableOpacity> }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#f8fafc'},container:{padding:24,paddingBottom:100},eyebrow:{fontSize:11,color:'#64748b',fontWeight:'600',letterSpacing:1},title:{fontSize:25,fontWeight:'700',color:'#0f172a',marginTop:8},muted:{fontSize:13,color:'#64748b',marginTop:6},punchCard:{backgroundColor:'#4f46e5',borderRadius:18,padding:22,marginTop:28},cardLabel:{color:'#c7d2fe',fontSize:11,fontWeight:'700',letterSpacing:1},time:{color:'#fff',fontSize:25,fontWeight:'700',marginVertical:14},button:{backgroundColor:'#fff',borderRadius:10,padding:13,alignItems:'center'},buttonText:{color:'#3730a3',fontWeight:'700'},grid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginTop:18},metric:{backgroundColor:'#fff',borderRadius:12,padding:16,width:'47%'},metricValue:{fontSize:18,fontWeight:'700',color:'#0f172a',marginTop:8},section:{fontSize:17,fontWeight:'700',marginTop:30,color:'#0f172a'},actions:{gap:10,marginTop:12},action:{backgroundColor:'#fff',padding:17,borderRadius:12},actionText:{color:'#3730a3',fontWeight:'600'},tabs:{position:'absolute',bottom:0,left:0,right:0,backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#e2e8f0',flexDirection:'row',justifyContent:'space-around',paddingVertical:14},tab:{alignItems:'center'},tabText:{fontSize:11,color:'#64748b'},tabActive:{color:'#4f46e5',fontWeight:'700'}});
